CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CUSTOMERS (
    ID          NUMBER(19)     PRIMARY KEY,
    FIRST_NAME  VARCHAR2(100)  NOT NULL,
    LAST_NAME   VARCHAR2(100)  NOT NULL,
    EMAIL       VARCHAR2(150)  NOT NULL UNIQUE,
    PHONE       VARCHAR2(20),
    CITY        VARCHAR2(100),
    CREATED_AT  TIMESTAMP      NOT NULL
);
